#!/bin/sh

# Force enable TRIM
if [ "${ACTION}" = "bind" -o "${ACTION}" = "add" ]; then
	case "${PRODUCT}" in
		# Vendor/ProdID/* (cat /sys/kernel/debug/usb/devices)
		174c/235c/*)
			prov_mode="$(find /sys${DEVPATH} -name provisioning_mode)"
			[ -e "${prov_mode}" ] && echo "unmap" > "${prov_mode}"
		;;
	esac
fi